//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2020/4/20 0:21:12]

using System.Collections;
using System.Collections.Generic;
using System.Data;

namespace tabtool
{

    public class TbsO:\Git\Saro\tabtool\csharptest\config\achive.txtItem
    {
        public type name;
        public int id;
        public string name;
        public int line;
        public tbsIdCount test1;
        public List<int> test2;
        public List<tbsKeyValue> test3;
    }

    public class CfgO:\Git\Saro\tabtool\csharptest\config\achive.txtTable : TableManager<TbsO:\Git\Saro\tabtool\csharptest\config\achive.txtItem, CfgO:\Git\Saro\tabtool\csharptest\config\achive.txtTable>
    {
        public override bool Load()
        {
            TableReader tr = new TableReader();
            DataReader dr = new DataReader();
            DataTable dt = tr.ReadFile(MyConfig.WorkDir+"O:\Git\Saro\tabtool\csharptest\config\achive.txt.txt");

            foreach(DataRow row in dt.Rows)
            {
                var item = new TbsO:\Git\Saro\tabtool\csharptest\config\achive.txtItem();
                  item.name = dr.GetObject<type>(row["name"].ToString());
                  item.id = dr.GetInt(row["id"].ToString());
                  item.name = (row["name"].ToString());
                  item.line = dr.GetInt(row["line"].ToString());
                  item.test1 = dr.GetObject<tbsIdCount>(row["test1"].ToString());
                  item.test2 = dr.GetIntList(row["test2"].ToString());
                  item.test3 = dr.GetObjectList<tbsKeyValue>(row["test3"].ToString());
                  m_Items[item.id] = item;
            }
            return true;
        }
    }

    public class TableConfig : SingletonTable<TableConfig>
    {
        public bool LoadTableConfig()
        {
            if (!CfgO:\Git\Saro\tabtool\csharptest\config\achive.txtTable.Instance.Load()) return false;
            return true;
        }
    }
}
