//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2020/4/27 2:48:12]

using System.Collections;
using System.Collections.Generic;
using System.Data;

namespace tabtool
{
    public class TableConfig : SingletonTable<TableConfig>
    {
        public bool LoadTableConfig()
        {
            return true;
        }
    }
}
