//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2020/4/25 5:11:27]

namespace tabtool
{
  public class tbsIdCount : ITableObject
  {
      public int id;
      public int count;
      public bool FromString(string s)
      {
          DataReader dr = new DataReader();

          var vs = s.Split(',');
          if (vs.Length != 2)
          {
              return false;
          }

		id = dr.GetInt(vs[0]);
		count = dr.GetInt(vs[1]);
          return true;
      }
  };

  public class tbsKeyValue : ITableObject
  {
      public int key;
      public int value;
      public bool FromString(string s)
      {
          DataReader dr = new DataReader();

          var vs = s.Split(',');
          if (vs.Length != 2)
          {
              return false;
          }

		key = dr.GetInt(vs[0]);
		value = dr.GetInt(vs[1]);
          return true;
      }
  };

  public class tbsTest : ITableObject
  {
      public int a;
      public string b;
      public float c;
      public bool FromString(string s)
      {
          DataReader dr = new DataReader();

          var vs = s.Split(',');
          if (vs.Length != 2)
          {
              return false;
          }

		a = dr.GetInt(vs[0]);
		b = vs[1];
		c = dr.GetFloat(vs[2]);
          return true;
      }
  };

}
