//------------------------------------------------------------------------------
// File   : TODO
// Author : Saro
// Time   : 2020/5/28 1:55:03
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tabtool
{
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Text;
    
    
    public class TbsITEMTable
    {
        
        /// key
        public int id;
        
        /// 描述
        public string name;
    }
    
    public class CfgITEMTable : TableBase<TbsITEMTable, CfgITEMTable>
    {
        
        public override bool Load()
        {
			var bytes = GetBytes("ITEM.txt");

			using (var ms = new MemoryStream(bytes))
			{
				using (var br = new BinaryReader(ms))
				{
					var version = br.ReadInt32();//version
					var dataLen = br.ReadInt32();
					for (int i = 0; i < dataLen; i++)
					{
						var data = new TbsITEMTable();
						data.id = br.ReadInt32();
						data.name = br.ReadString();
						m_Datas[data.id] = data;
					}
				}
			}

            return true;
        }
        
        public override string ToString()
        {
			var sb = new StringBuilder(1024);
			foreach (var data in m_Datas.Values)
			{
				sb.Append(data.id).Append("\t");
				sb.Append(data.name).Append("\t");
				sb.AppendLine();
			}

            return sb.ToString();
        }
    }
}
